import News from "../news/news.model.js";
import Quiz from "./quiz.model.js";
import { callDeepSeek } from "../../services/ai.service.js";
import axios from "axios";
import cron from "node-cron";

const QUIZ_PROMPT = `Generate exactly 5 multiple-choice questions from the provided article content. 
Rules:
- 4 options per question.
- 1 correct answer.
- Do NOT invent facts.
- Return ONLY a valid JSON array in this format:
[
  {
    "question": "text",
    "options": ["a", "b", "c", "d"],
    "correctAnswer": "exact string match from options",
    "explanation": "text"
  }
]`;

export const generateQuizFromNewsId = async (newsId) => {
    const news = await News.findById(newsId);
    if (!news || !news.rewrittenContent) throw new Error("Rewritten content required for quiz");

    const existing = await Quiz.findOne({ newsId });
    if (existing) return existing;

    console.log(`🧠 AI MCQ Generation: ${news.title.substring(0, 30)}...`);

    const aiResponse = await callDeepSeek(QUIZ_PROMPT, news.rewrittenContent);
    const questions = JSON.parse(aiResponse.replace(/```json|```/g, ""));

    return await Quiz.create({
        category: news.category,
        newsId: news._id,
        questions
    });
};

export const autoGenerateDailyCategoryQuiz = async () => {
    console.log("🧠 Starting Daily Quiz Auto-Generation...");
    const categories = await News.distinct("category", { isToday: true });

    for (const category of categories) {
        try {
            const latestNews = await News.findOne({ category, isToday: true })
                .sort({ publishedAt: -1 });

            if (!latestNews || !latestNews.rewrittenContent) continue;

            const existingQuiz = await Quiz.findOne({
                category,
                createdAt: { $gte: new Date().setHours(0, 0, 0, 0) }
            });

            if (existingQuiz) continue;

            const aiResponse = await callDeepSeek(QUIZ_PROMPT, latestNews.rewrittenContent);
            const questions = JSON.parse(aiResponse.replace(/```json|```/g, ""));

            await Quiz.create({
                category,
                newsId: latestNews._id,
                questions
            });

            console.log(`✅ Daily Quiz Generated for Category: ${category}`);
        } catch (err) {
            console.error(`❌ Failed to auto-gen quiz for ${category}:`, err.message);
        }
    }
};

export const generateQuizFromSource = async (urlOrContent) => {
    let content = urlOrContent;
    if (urlOrContent.startsWith("http")) {
        const res = await axios.get(urlOrContent);
        content = res.data;
    }

    const aiResponse = await callDeepSeek(QUIZ_PROMPT, content);
    const questions = JSON.parse(aiResponse.replace(/```json|```/g, ""));

    return await Quiz.create({
        category: "custom",
        questions
    });
};

export const getQuestionsByCategory = async (category) => {
    const quiz = await Quiz.findOne({ category }).sort({ createdAt: -1 });
    if (!quiz) throw new Error(`No quiz found for category: ${category}`);
    return quiz;
};

// 🔥 DAILY CRON: Generate quizzes at Midnight
cron.schedule("0 0 * * *", async () => {
    await autoGenerateDailyCategoryQuiz().catch(err => console.error("Daily Quiz Cron Error:", err.message));
});
