import News from "../../models/News.js";
import Quiz from "./quiz.model.js";
import { callDeepSeek } from "../../services/aiService.js";
import axios from "axios";
import cron from "node-cron";

const QUIZ_PROMPT = `Generate 5 multiple-choice questions from the provided news content. 
Rules:
- 4 options per question.
- 1 correct answer (exact string match from options).
- Provide a catchy title, a short description, and a difficulty level (easy, medium, or hard).
- Return ONLY a valid JSON object in this format:
{
  "title": "Catchy Title here",
  "description": "Short summary description of the quiz",
  "difficulty": "medium",
  "questions": [
    {
      "question": "text",
      "options": ["a", "b", "c", "d"],
      "correctAnswer": "exact string match from options",
      "explanation": "Brief explanation"
    }
  ]
}`;

export const generateQuizFromNewsId = async (newsId) => {
    const news = await News.findById(newsId);
    if (!news || !news.rewrittenContent) throw new Error("Rewritten content required for quiz");

    const existing = await Quiz.findOne({ newsId });
    if (existing) return existing;

    console.log(`🧠 AI MCQ Generation: ${news.title.substring(0, 30)}...`);

    const aiResponse = await callDeepSeek(QUIZ_PROMPT, news.rewrittenContent);
    const data = JSON.parse(aiResponse.replace(/```json|```/g, ""));

    return await Quiz.create({
        title: data.title || `${news.category} Quiz`,
        description: data.description || `Test your knowledge about this news.`,
        category: news.category,
        difficulty: data.difficulty || "medium",
        newsId: news._id,
        questions: data.questions
    });
};

export const autoGenerateDailyCategoryQuiz = async () => {
    console.log("🧠 Starting Daily Quiz Auto-Generation...");
    const categories = await News.distinct("category", { isToday: true });

    for (const category of categories) {
        try {
            const latestNews = await News.findOne({ category, isToday: true })
                .sort({ publishedAt: -1 });

            if (!latestNews || !latestNews.rewrittenContent) continue;

            const existingQuiz = await Quiz.findOne({
                category,
                createdAt: { $gte: new Date().setHours(0, 0, 0, 0) }
            });

            if (existingQuiz) continue;

            const aiResponse = await callDeepSeek(QUIZ_PROMPT, latestNews.rewrittenContent);
            const data = JSON.parse(aiResponse.replace(/```json|```/g, ""));

            await Quiz.create({
                title: data.title || `${category} Quiz`,
                description: data.description || `Daily quiz on ${category} news.`,
                category,
                difficulty: data.difficulty || "easy",
                newsId: latestNews._id,
                questions: data.questions
            });

            console.log(`✅ Daily Quiz Generated for Category: ${category}`);
        } catch (err) {
            console.error(`❌ Failed to auto-gen quiz for ${category}:`, err.message);
        }
    }
};

export const generateQuizFromSource = async (urlOrContent) => {
    let content = urlOrContent;
    if (urlOrContent.startsWith("http")) {
        try {
            const res = await axios.get(urlOrContent, { timeout: 10000 });
            // Very basic HTML strip to reduce tokens and noise
            const rawData = res.data ? (typeof res.data === 'string' ? res.data : JSON.stringify(res.data)) : "";
            content = rawData.replace(/<[^>]*>?/gm, ' ').substring(0, 10000);
        } catch (err) {
            console.error("URL Fetch Error:", err.message);
            content = urlOrContent; // Fallback to raw URL string, AI might know it
        }
    }

    const aiResponse = await callDeepSeek(QUIZ_PROMPT, content);

    let data;
    try {
        // More robust JSON extraction
        const jsonMatch = aiResponse.match(/\{[\s\S]*\}/);
        if (!jsonMatch) throw new Error("No JSON found in AI response");
        data = JSON.parse(jsonMatch[0]);
    } catch (err) {
        console.error("AI Parse Error:", err.message, aiResponse);
        throw new Error("Failed to parse AI-generated quiz. Please try again.");
    }

    if (!data.questions || !Array.isArray(data.questions) || data.questions.length === 0) {
        throw new Error("AI failed to generate valid questions. Try providing more text.");
    }

    return await Quiz.create({
        title: data.title || "Custom Quiz",
        description: data.description || "Experimental custom quiz.",
        category: "General",
        difficulty: data.difficulty || "medium",
        questions: data.questions
    });
};

export const getQuestionsByCategory = async (category) => {
    const quiz = await Quiz.findOne({ category }).sort({ createdAt: -1 });
    if (!quiz) throw new Error(`No quiz found for category: ${category}`);
    return quiz;
};

// 🔥 DAILY CRON: Generate quizzes at Midnight
cron.schedule("0 0 * * *", async () => {
    await autoGenerateDailyCategoryQuiz().catch(err => console.error("Daily Quiz Cron Error:", err.message));
});
